POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8081/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
POST  http://localhost:8081/user/deleteAll


### User Login (Get JWT Token)
POST http://localhost:8081/user/login
Content-Type: application/json

{
  "username": "tochiamanze",
  "password": "tochi12345"
}


### Like a Movie (Add to Favorites)
POST http://localhost:8081/user/635ab8dfc407faf9f73deaf1/favorites
Content-Type: application/json

{
  "movieId": "tt1637725",
  "title": "Inception"
}

### Remove a movie from favorites
DELETE http://localhost:8081/user/635ab8dfc407faf9f73deaf1/favorites/tt1637725
Content-Type: application/json

### Get a user's favorite movies
GET http://localhost:8081/user/635ab8dfc407faf9f73deaf1/favorites


### Add a comment
# The movie Id 'tt0084787'
POST http://localhost:8081/api/movies/tt0084787/comments
Content-Type: application/json

{
  "userId": "65d5f3d2a3b4d8e1a2c9e4f6",
  "text": "This movie was amazing!"
}

### Get comments for a movie
GET http://localhost:8081/api/movies/tt0084787/comments


### Get movie info
GET http://localhost:8080/api/movie?title=Inception
